# WebSphere Liberty base image
FROM ibmcom/websphere-liberty:kernel-java8-openj9-ubi

# Add config and app
COPY --chown=1001:0 src/main/liberty/config/server.xml /config/server.xml
COPY --chown=1001:0 target/usr/servers/defaultServer/bootstrap.properties /opt/ol/ibm/usr/shared/bootstrap.properties
COPY --chown=1001:0 target/${project.artifactId}.war /config/apps/


# This script will add the requested XML snippets, grow image to be fit-for-purpose and apply interim fixes
RUN configure.sh
